import { MinecraftItemTypes } from "@minecraft/vanilla-data";

export const itemValues: Record<string, number> = {
  [MinecraftItemTypes.Potion]: 35,
  [MinecraftItemTypes.MilkBucket]: 20,
  [MinecraftItemTypes.HoneyBottle]: 12,
  [MinecraftItemTypes.BeetrootSoup]: 28,
  [MinecraftItemTypes.MushroomStew]: 24,
  [MinecraftItemTypes.RabbitStew]: 30,
  [MinecraftItemTypes.SuspiciousStew]: 22,
  [MinecraftItemTypes.MelonSlice]: 12,
  [MinecraftItemTypes.Apple]: 8,
  [MinecraftItemTypes.GoldenApple]: 15,
  [MinecraftItemTypes.EnchantedGoldenApple]: 35,
  [MinecraftItemTypes.GoldenCarrot]: 10,
  [MinecraftItemTypes.GlowBerries]: 7,
  [MinecraftItemTypes.SweetBerries]: 6,
  [MinecraftItemTypes.Beetroot]: 5,
  [MinecraftItemTypes.Carrot]: 6,
  [MinecraftItemTypes.Potato]: 2,
  [MinecraftItemTypes.BakedPotato]: -6,
  [MinecraftItemTypes.DriedKelp]: -8,
  [MinecraftItemTypes.ChorusFruit]: 6,
  [MinecraftItemTypes.Bread]: -7,
  [MinecraftItemTypes.Cookie]: -6,
  [MinecraftItemTypes.PumpkinPie]: -5,
  [MinecraftItemTypes.Cod]: 4,
  [MinecraftItemTypes.Salmon]: 4,
  [MinecraftItemTypes.TropicalFish]: 3,
  [MinecraftItemTypes.CookedCod]: -5,
  [MinecraftItemTypes.CookedSalmon]: -5,
  [MinecraftItemTypes.Beef]: -4,
  [MinecraftItemTypes.Chicken]: -4,
  [MinecraftItemTypes.Mutton]: -4,
  [MinecraftItemTypes.Porkchop]: -4,
  [MinecraftItemTypes.Rabbit]: -3,
  [MinecraftItemTypes.CookedBeef]: -12,
  [MinecraftItemTypes.CookedChicken]: -10,
  [MinecraftItemTypes.CookedMutton]: -12,
  [MinecraftItemTypes.CookedPorkchop]: -12,
  [MinecraftItemTypes.CookedRabbit]: -8,
  [MinecraftItemTypes.Pufferfish]: -25,
  [MinecraftItemTypes.PoisonousPotato]: -20,
  [MinecraftItemTypes.RottenFlesh]: -18,
  [MinecraftItemTypes.SpiderEye]: -20,
  [MinecraftItemTypes.OminousBottle]: -30,
};
