/**
 * Configuration for the hydration system
 */

import { MinecraftBiomeTypes, MinecraftItemTypes } from "@minecraft/vanilla-data";
import { IHydrationConfig } from "./types/hydration";

const itemValues: Record<string, number> = {
  [MinecraftItemTypes.Potion]: 35,
  [MinecraftItemTypes.MilkBucket]: 20,
  [MinecraftItemTypes.HoneyBottle]: 12,
  [MinecraftItemTypes.BeetrootSoup]: 28,
  [MinecraftItemTypes.MushroomStew]: 24,
  [MinecraftItemTypes.RabbitStew]: 30,
  [MinecraftItemTypes.SuspiciousStew]: 22,
  [MinecraftItemTypes.MelonSlice]: 12,
  [MinecraftItemTypes.Apple]: 8,
  [MinecraftItemTypes.GoldenApple]: 15,
  [MinecraftItemTypes.EnchantedGoldenApple]: 35,
  [MinecraftItemTypes.GoldenCarrot]: 10,
  [MinecraftItemTypes.GlowBerries]: 7,
  [MinecraftItemTypes.SweetBerries]: 6,
  [MinecraftItemTypes.Beetroot]: 5,
  [MinecraftItemTypes.Carrot]: 6,
  [MinecraftItemTypes.Potato]: 2,
  [MinecraftItemTypes.BakedPotato]: -6,
  [MinecraftItemTypes.DriedKelp]: -8,
  [MinecraftItemTypes.ChorusFruit]: 6,
  [MinecraftItemTypes.Bread]: -7,
  [MinecraftItemTypes.Cookie]: -6,
  [MinecraftItemTypes.PumpkinPie]: -5,
  [MinecraftItemTypes.Cod]: 4,
  [MinecraftItemTypes.Salmon]: 4,
  [MinecraftItemTypes.TropicalFish]: 3,
  [MinecraftItemTypes.CookedCod]: -5,
  [MinecraftItemTypes.CookedSalmon]: -5,
  [MinecraftItemTypes.Beef]: -4,
  [MinecraftItemTypes.Chicken]: -4,
  [MinecraftItemTypes.Mutton]: -4,
  [MinecraftItemTypes.Porkchop]: -4,
  [MinecraftItemTypes.Rabbit]: -3,
  [MinecraftItemTypes.CookedBeef]: -12,
  [MinecraftItemTypes.CookedChicken]: -10,
  [MinecraftItemTypes.CookedMutton]: -12,
  [MinecraftItemTypes.CookedPorkchop]: -12,
  [MinecraftItemTypes.CookedRabbit]: -8,
  [MinecraftItemTypes.Pufferfish]: -25,
  [MinecraftItemTypes.PoisonousPotato]: -20,
  [MinecraftItemTypes.RottenFlesh]: -18,
  [MinecraftItemTypes.SpiderEye]: -20,
  [MinecraftItemTypes.OminousBottle]: -30,
};

const dimensionMultipliers = {
  "minecraft:overworld": 1.0,
  "minecraft:nether": 2.0,
  "minecraft:end": 1.5,
};

const biomeMultipliers: Record<string, number> = {
  [MinecraftBiomeTypes.BambooJungle]: 0.85,
  [MinecraftBiomeTypes.BambooJungleHills]: 0.85,
  [MinecraftBiomeTypes.BasaltDeltas]: 1.35,
  [MinecraftBiomeTypes.Beach]: 1.05,
  [MinecraftBiomeTypes.BirchForest]: 0.95,
  [MinecraftBiomeTypes.BirchForestHills]: 0.95,
  [MinecraftBiomeTypes.BirchForestHillsMutated]: 0.95,
  [MinecraftBiomeTypes.BirchForestMutated]: 0.95,
  [MinecraftBiomeTypes.CherryGrove]: 0.9,
  [MinecraftBiomeTypes.ColdBeach]: 0.9,
  [MinecraftBiomeTypes.ColdOcean]: 0.9,
  [MinecraftBiomeTypes.ColdTaiga]: 0.9,
  [MinecraftBiomeTypes.ColdTaigaHills]: 0.9,
  [MinecraftBiomeTypes.ColdTaigaMutated]: 0.9,
  [MinecraftBiomeTypes.CrimsonForest]: 1.25,
  [MinecraftBiomeTypes.DeepColdOcean]: 0.85,
  [MinecraftBiomeTypes.DeepDark]: 0.95,
  [MinecraftBiomeTypes.DeepFrozenOcean]: 0.8,
  [MinecraftBiomeTypes.DeepLukewarmOcean]: 0.95,
  [MinecraftBiomeTypes.DeepOcean]: 0.95,
  [MinecraftBiomeTypes.DeepWarmOcean]: 1.1,
  [MinecraftBiomeTypes.Desert]: 1.5,
  [MinecraftBiomeTypes.DesertHills]: 1.5,
  [MinecraftBiomeTypes.DesertMutated]: 1.5,
  [MinecraftBiomeTypes.DripstoneCaves]: 1,
  [MinecraftBiomeTypes.ExtremeHills]: 1.05,
  [MinecraftBiomeTypes.ExtremeHillsEdge]: 1,
  [MinecraftBiomeTypes.ExtremeHillsMutated]: 1.05,
  [MinecraftBiomeTypes.ExtremeHillsPlusTrees]: 1,
  [MinecraftBiomeTypes.ExtremeHillsPlusTreesMutated]: 1,
  [MinecraftBiomeTypes.FlowerForest]: 0.9,
  [MinecraftBiomeTypes.Forest]: 0.95,
  [MinecraftBiomeTypes.ForestHills]: 0.95,
  [MinecraftBiomeTypes.FrozenOcean]: 0.85,
  [MinecraftBiomeTypes.FrozenPeaks]: 0.75,
  [MinecraftBiomeTypes.FrozenRiver]: 0.8,
  [MinecraftBiomeTypes.Grove]: 0.8,
  [MinecraftBiomeTypes.Hell]: 1.3,
  [MinecraftBiomeTypes.IceMountains]: 0.8,
  [MinecraftBiomeTypes.IcePlains]: 0.8,
  [MinecraftBiomeTypes.IcePlainsSpikes]: 0.75,
  [MinecraftBiomeTypes.JaggedPeaks]: 0.8,
  [MinecraftBiomeTypes.Jungle]: 0.85,
  [MinecraftBiomeTypes.JungleEdge]: 0.9,
  [MinecraftBiomeTypes.JungleEdgeMutated]: 0.9,
  [MinecraftBiomeTypes.JungleHills]: 0.85,
  [MinecraftBiomeTypes.JungleMutated]: 0.85,
  [MinecraftBiomeTypes.LegacyFrozenOcean]: 0.85,
  [MinecraftBiomeTypes.LukewarmOcean]: 1,
  [MinecraftBiomeTypes.LushCaves]: 0.8,
  [MinecraftBiomeTypes.MangroveSwamp]: 0.8,
  [MinecraftBiomeTypes.Meadow]: 0.9,
  [MinecraftBiomeTypes.MegaTaiga]: 0.95,
  [MinecraftBiomeTypes.MegaTaigaHills]: 0.95,
  [MinecraftBiomeTypes.Mesa]: 1.4,
  [MinecraftBiomeTypes.MesaBryce]: 1.45,
  [MinecraftBiomeTypes.MesaPlateau]: 1.35,
  [MinecraftBiomeTypes.MesaPlateauMutated]: 1.35,
  [MinecraftBiomeTypes.MesaPlateauStone]: 1.3,
  [MinecraftBiomeTypes.MesaPlateauStoneMutated]: 1.3,
  [MinecraftBiomeTypes.MushroomIsland]: 0.95,
  [MinecraftBiomeTypes.MushroomIslandShore]: 0.95,
  [MinecraftBiomeTypes.Ocean]: 0.95,
  [MinecraftBiomeTypes.PaleGarden]: 0.9,
  [MinecraftBiomeTypes.Plains]: 1,
  [MinecraftBiomeTypes.RedwoodTaigaHillsMutated]: 0.95,
  [MinecraftBiomeTypes.RedwoodTaigaMutated]: 0.95,
  [MinecraftBiomeTypes.River]: 0.9,
  [MinecraftBiomeTypes.RoofedForest]: 0.95,
  [MinecraftBiomeTypes.RoofedForestMutated]: 0.95,
  [MinecraftBiomeTypes.Savanna]: 1.25,
  [MinecraftBiomeTypes.SavannaMutated]: 1.3,
  [MinecraftBiomeTypes.SavannaPlateau]: 1.25,
  [MinecraftBiomeTypes.SavannaPlateauMutated]: 1.3,
  [MinecraftBiomeTypes.SnowySlopes]: 0.8,
  [MinecraftBiomeTypes.SoulsandValley]: 1.35,
  [MinecraftBiomeTypes.StoneBeach]: 1,
  [MinecraftBiomeTypes.StonyPeaks]: 0.95,
  [MinecraftBiomeTypes.SunflowerPlains]: 1,
  [MinecraftBiomeTypes.Swampland]: 0.8,
  [MinecraftBiomeTypes.SwamplandMutated]: 0.8,
  [MinecraftBiomeTypes.Taiga]: 0.95,
  [MinecraftBiomeTypes.TaigaHills]: 0.95,
  [MinecraftBiomeTypes.TaigaMutated]: 0.95,
  [MinecraftBiomeTypes.TheEnd]: 1.1,
  [MinecraftBiomeTypes.WarmOcean]: 1.1,
  [MinecraftBiomeTypes.WarpedForest]: 1.15,
};

const exertionValues = {
  walk: 0.01,
  sprint: 0.04,
  jump: 0.08,
  swing: 0.05,
};

const daytimeMultiplier = {
  midnight: 0.85,
  noon: 1.3,
};

const dryBiomes = [
  MinecraftBiomeTypes.Desert,
  MinecraftBiomeTypes.DesertHills,
  MinecraftBiomeTypes.DesertMutated,
  MinecraftBiomeTypes.Mesa,
  MinecraftBiomeTypes.MesaBryce,
  MinecraftBiomeTypes.MesaPlateau,
  MinecraftBiomeTypes.MesaPlateauMutated,
  MinecraftBiomeTypes.MesaPlateauStone,
  MinecraftBiomeTypes.MesaPlateauStoneMutated,
  MinecraftBiomeTypes.Savanna,
  MinecraftBiomeTypes.SavannaMutated,
  MinecraftBiomeTypes.SavannaPlateau,
  MinecraftBiomeTypes.SavannaPlateauMutated,
];

const weatherMultiplier = {
  rain: 0.75,
  thunder: 0.65,
  dryBiomes: dryBiomes,
};

const skyExposureMultiplier = {
  sheltered: 0.8,
  exposed: 1.25,
};

export const HYDRATION_CONFIG: IHydrationConfig = {
  baseDrainRate: 0.01, // Base hydration drain rate per tick
  tickInterval: 20, // Number of ticks between hydration updates
  uiTickInterval: 5, // Number of ticks between hydration UI refreshes
  punishTickInterval: 40, // Number of ticks between hydration consequences are applied
  maxHydration: 100, // Maximum hydration level
  criticalThreshold: 20, // Hydration level considered critical
  exertionValues: exertionValues,
  daytimeMultiplier: daytimeMultiplier,
  weatherMultiplier: weatherMultiplier,
  skyExposureMultiplier: skyExposureMultiplier,
  itemValues: itemValues,
  biomeMultipliers: biomeMultipliers,
  dimensionMultipliers: dimensionMultipliers,
};
