/**
 * Configuration for the hydration system
 */

import { MinecraftBiomeTypes, MinecraftItemTypes } from "@minecraft/vanilla-data";
import { IHydrationConfig } from "./types/hydration";

const itemValues: Record<string, number> = {
  [MinecraftItemTypes.Potion]: 12,
  [MinecraftItemTypes.MilkBucket]: 8,
  [MinecraftItemTypes.HoneyBottle]: 10,
  [MinecraftItemTypes.BeetrootSoup]: 16,
  [MinecraftItemTypes.MushroomStew]: 14,
  [MinecraftItemTypes.RabbitStew]: 18,
  [MinecraftItemTypes.SuspiciousStew]: 12,
  [MinecraftItemTypes.MelonSlice]: 6,
  [MinecraftItemTypes.Apple]: 4,
  [MinecraftItemTypes.GoldenApple]: 8,
  [MinecraftItemTypes.EnchantedGoldenApple]: 12,
  [MinecraftItemTypes.GoldenCarrot]: 5,
  [MinecraftItemTypes.GlowBerries]: 4,
  [MinecraftItemTypes.SweetBerries]: 3,
  [MinecraftItemTypes.Beetroot]: 2,
  [MinecraftItemTypes.Carrot]: 3,
  [MinecraftItemTypes.Potato]: 1,
  [MinecraftItemTypes.BakedPotato]: 2,
  [MinecraftItemTypes.DriedKelp]: 1,
  [MinecraftItemTypes.ChorusFruit]: 3,
  [MinecraftItemTypes.Bread]: -1,
  [MinecraftItemTypes.Cookie]: -1,
  [MinecraftItemTypes.PumpkinPie]: -2,
  [MinecraftItemTypes.Cod]: 2,
  [MinecraftItemTypes.Salmon]: 2,
  [MinecraftItemTypes.TropicalFish]: 1,
  [MinecraftItemTypes.CookedCod]: 1,
  [MinecraftItemTypes.CookedSalmon]: 1,
  [MinecraftItemTypes.Beef]: -2,
  [MinecraftItemTypes.Chicken]: -2,
  [MinecraftItemTypes.Mutton]: -2,
  [MinecraftItemTypes.Porkchop]: -2,
  [MinecraftItemTypes.Rabbit]: -1,
  [MinecraftItemTypes.CookedBeef]: -4,
  [MinecraftItemTypes.CookedChicken]: -4,
  [MinecraftItemTypes.CookedMutton]: -4,
  [MinecraftItemTypes.CookedPorkchop]: -4,
  [MinecraftItemTypes.CookedRabbit]: -3,
  [MinecraftItemTypes.Pufferfish]: -12,
  [MinecraftItemTypes.PoisonousPotato]: -10,
  [MinecraftItemTypes.RottenFlesh]: -8,
  [MinecraftItemTypes.SpiderEye]: -10,
  [MinecraftItemTypes.OminousBottle]: -15,
};

const dimensionMultipliers = {
  "minecraft:overworld": 1.0,
  "minecraft:nether": 1.5,
  "minecraft:end": 1.2,
};

const biomeMultipliers: Record<string, number> = {
  [MinecraftBiomeTypes.BambooJungle]: 0.85,
  [MinecraftBiomeTypes.BambooJungleHills]: 0.85,
  [MinecraftBiomeTypes.BasaltDeltas]: 1.35,
  [MinecraftBiomeTypes.Beach]: 1.05,
  [MinecraftBiomeTypes.BirchForest]: 0.95,
  [MinecraftBiomeTypes.BirchForestHills]: 0.95,
  [MinecraftBiomeTypes.BirchForestHillsMutated]: 0.95,
  [MinecraftBiomeTypes.BirchForestMutated]: 0.95,
  [MinecraftBiomeTypes.CherryGrove]: 0.9,
  [MinecraftBiomeTypes.ColdBeach]: 0.9,
  [MinecraftBiomeTypes.ColdOcean]: 0.9,
  [MinecraftBiomeTypes.ColdTaiga]: 0.9,
  [MinecraftBiomeTypes.ColdTaigaHills]: 0.9,
  [MinecraftBiomeTypes.ColdTaigaMutated]: 0.9,
  [MinecraftBiomeTypes.CrimsonForest]: 1.25,
  [MinecraftBiomeTypes.DeepColdOcean]: 0.85,
  [MinecraftBiomeTypes.DeepDark]: 0.95,
  [MinecraftBiomeTypes.DeepFrozenOcean]: 0.8,
  [MinecraftBiomeTypes.DeepLukewarmOcean]: 0.95,
  [MinecraftBiomeTypes.DeepOcean]: 0.95,
  [MinecraftBiomeTypes.DeepWarmOcean]: 1.1,
  [MinecraftBiomeTypes.Desert]: 1.5,
  [MinecraftBiomeTypes.DesertHills]: 1.5,
  [MinecraftBiomeTypes.DesertMutated]: 1.5,
  [MinecraftBiomeTypes.DripstoneCaves]: 1,
  [MinecraftBiomeTypes.ExtremeHills]: 1.05,
  [MinecraftBiomeTypes.ExtremeHillsEdge]: 1,
  [MinecraftBiomeTypes.ExtremeHillsMutated]: 1.05,
  [MinecraftBiomeTypes.ExtremeHillsPlusTrees]: 1,
  [MinecraftBiomeTypes.ExtremeHillsPlusTreesMutated]: 1,
  [MinecraftBiomeTypes.FlowerForest]: 0.9,
  [MinecraftBiomeTypes.Forest]: 0.95,
  [MinecraftBiomeTypes.ForestHills]: 0.95,
  [MinecraftBiomeTypes.FrozenOcean]: 0.85,
  [MinecraftBiomeTypes.FrozenPeaks]: 0.75,
  [MinecraftBiomeTypes.FrozenRiver]: 0.8,
  [MinecraftBiomeTypes.Grove]: 0.8,
  [MinecraftBiomeTypes.Hell]: 1.3,
  [MinecraftBiomeTypes.IceMountains]: 0.8,
  [MinecraftBiomeTypes.IcePlains]: 0.8,
  [MinecraftBiomeTypes.IcePlainsSpikes]: 0.75,
  [MinecraftBiomeTypes.JaggedPeaks]: 0.8,
  [MinecraftBiomeTypes.Jungle]: 0.85,
  [MinecraftBiomeTypes.JungleEdge]: 0.9,
  [MinecraftBiomeTypes.JungleEdgeMutated]: 0.9,
  [MinecraftBiomeTypes.JungleHills]: 0.85,
  [MinecraftBiomeTypes.JungleMutated]: 0.85,
  [MinecraftBiomeTypes.LegacyFrozenOcean]: 0.85,
  [MinecraftBiomeTypes.LukewarmOcean]: 1,
  [MinecraftBiomeTypes.LushCaves]: 0.8,
  [MinecraftBiomeTypes.MangroveSwamp]: 0.8,
  [MinecraftBiomeTypes.Meadow]: 0.9,
  [MinecraftBiomeTypes.MegaTaiga]: 0.95,
  [MinecraftBiomeTypes.MegaTaigaHills]: 0.95,
  [MinecraftBiomeTypes.Mesa]: 1.4,
  [MinecraftBiomeTypes.MesaBryce]: 1.45,
  [MinecraftBiomeTypes.MesaPlateau]: 1.35,
  [MinecraftBiomeTypes.MesaPlateauMutated]: 1.35,
  [MinecraftBiomeTypes.MesaPlateauStone]: 1.3,
  [MinecraftBiomeTypes.MesaPlateauStoneMutated]: 1.3,
  [MinecraftBiomeTypes.MushroomIsland]: 0.95,
  [MinecraftBiomeTypes.MushroomIslandShore]: 0.95,
  [MinecraftBiomeTypes.Ocean]: 0.95,
  [MinecraftBiomeTypes.PaleGarden]: 0.9,
  [MinecraftBiomeTypes.Plains]: 1,
  [MinecraftBiomeTypes.RedwoodTaigaHillsMutated]: 0.95,
  [MinecraftBiomeTypes.RedwoodTaigaMutated]: 0.95,
  [MinecraftBiomeTypes.River]: 0.9,
  [MinecraftBiomeTypes.RoofedForest]: 0.95,
  [MinecraftBiomeTypes.RoofedForestMutated]: 0.95,
  [MinecraftBiomeTypes.Savanna]: 1.25,
  [MinecraftBiomeTypes.SavannaMutated]: 1.3,
  [MinecraftBiomeTypes.SavannaPlateau]: 1.25,
  [MinecraftBiomeTypes.SavannaPlateauMutated]: 1.3,
  [MinecraftBiomeTypes.SnowySlopes]: 0.8,
  [MinecraftBiomeTypes.SoulsandValley]: 1.35,
  [MinecraftBiomeTypes.StoneBeach]: 1,
  [MinecraftBiomeTypes.StonyPeaks]: 0.95,
  [MinecraftBiomeTypes.SunflowerPlains]: 1,
  [MinecraftBiomeTypes.Swampland]: 0.8,
  [MinecraftBiomeTypes.SwamplandMutated]: 0.8,
  [MinecraftBiomeTypes.Taiga]: 0.95,
  [MinecraftBiomeTypes.TaigaHills]: 0.95,
  [MinecraftBiomeTypes.TaigaMutated]: 0.95,
  [MinecraftBiomeTypes.TheEnd]: 1.1,
  [MinecraftBiomeTypes.WarmOcean]: 1.1,
  [MinecraftBiomeTypes.WarpedForest]: 1.15,
};

export const HYDRATION_CONFIG: IHydrationConfig = {
  baseDrainRate: 0.1, // Base hydration drain rate per tick
  tickInterval: 20, // Number of ticks between hydration updates
  maxHydration: 100, // Maximum hydration level
  criticalThreshold: 20, // Hydration level considered critical
  itemValues: itemValues,
  biomeMultipliers: biomeMultipliers,
  dimensionMultipliers: dimensionMultipliers,
};
